### ISSUE TITLE
Facebook share opens a blank new page on mobile

### ISSUE THREAD

**Issue by daco** [MurhafSousli/ng2-sharebuttons#97] opened 2017-04-04 11:15 UTC
At least in iOs 10.3 Facebook share opens a blank page.
If I change the mobile link (fb://.....) in share-buttons.service

`        /** check for mobile browser (this won't detect tablets browser) */
        if (this.window.innerWidth <= 480) {
            args = Object.assign({}, args, { mobile: false });
        }`

back to the 'normal' link by setting mobile to false, the opened page shows the default Facebook share dialog in mobile Safari.

**Comment by MurhafSousli** [comment] 2017-04-04 11:41
If the application of the button is not installed, it will show blank page

**Comment by daco** [comment] 2017-04-04 11:43
Hi Murhaf,

Thanks for your reaction. I've got the app, in this case Facebook, installed.

**Comment by MurhafSousli** [comment] 2017-04-04 11:45
I see, this is only happening on safari

**Comment by daco** [comment] 2017-04-04 11:46
Also, would a popup needed when opening a link like fb:// ?

**Comment by MurhafSousli** [comment] 2017-04-04 11:57
Try the demo on safari.. it isn't showing a blank popup, It asks to open the app, however the issue is with fb and twitter not showing the dialog after opening, other buttons are working properly.
For opening a link with popup, this depends on the browser behavior, on safari it opens the app without popup

**Comment by MurhafSousli** [comment] 2017-04-04 12:03
Ok Safari is behaving weird, one time it asks to open the app, other time it popup a blank page.. I need to look into this

**Comment by daco** [comment] 2017-04-04 12:05
Interesting! The demo works (sorry I didn't test before filing this report), but opens a new window in Safari instead of using the app. This is fine with me by the way.
I'll investigate further and report if I find something.

**Comment by daco** [comment] 2017-04-04 14:48
Regarding my statement about your demo working.
It does in fact not work on iOS 10.3. In order to hit the FB button, I had to hold my iPhone in landscape, because otherwise the FB button would fall off. In landscape however, the line (this.window.innerWidth <= 480) evals to false, thereby keeping the desktop share link instead of fb:// scheme. Thats why I thought that it was working, but in Safari and not in the native app.
Googling around also learned me that this fb:// scheme is not officially supported, and indeed is not working on my phone. Moreover, I looks that even if it works on somebodies setup, the fb:// link only opens the FB app, but does not present you with the page you wish to share.

So, may I suggest two things.
1. Better mobile browser detection.
Maybe something like

`if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) { args = Object.assign({}, args, { mobile: false }); }`

Not very Angular-like, I know

2. Make using these schemes optional by passing [useMobileScheme]="false" or something, so that the developer can decide what to use.

**Comment by MurhafSousli** [comment] 2017-04-04 15:50
@daco Thanks for your investigation, however

1. Is not going to be better because user agent is a not a reliable solution, and it is never up to date
([we had a discussion about it here](https://github.com/MurhafSousli/ng2-sharebuttons/pull/90))

2. Is nice to have

We have been looking for a mobile detection solution but it is not happening at this time, we are not very satisfied with the current one `innerWidth` but it is the best so far.

If we don't use the native apps links, users will need to login through their browsers, and since everyone is using their apps, this will cause bad experience, users are most likely to change their minds and will give up on sharing because they forgot their password or any other reason.

For now let's keep this thread open until we figure out a solution for fb, linked, twitter native app links.

**Comment by MurhafSousli** [comment] 2017-04-05 12:27
That's right we are not considering using the sdk or any external script. It seems that facebook does not support sharing links though the app directly. I read [here](https://developers.facebook.com/docs/applinks/ios)

> Beginning with iOS 10, iOS doesn't support deferred deep linking, so you can't open content other than the starting screen once people have installed the app.

It's confusing, It is better to use the normal browser method for facebook

**Comment by MurhafSousli** [comment] 2017-04-11 14:33
closed in #101

**Closed by MurhafSousli** 2017-04-11 14:33 UTC
Labels: need: investigation
